name: web client PR check

on:
  push:
    branches:
      - "main"
      - "develop"
    paths:
      - "web/client/**"
      - ".github/workflows/web_client_pr_check.yml"

jobs:
  client:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]

    defaults:
      run:
        working-directory: web/client

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: ./web/client/pnpm-lock.json

      - name: Enable pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - run: pnpm lint
      - run: pnpm format -- --write=false

      # - name: Test
      #   run: npm run test

      - run: pnpm exec tsc --noEmit
      - run: pnpm build