name: web client PR check

on:
  push:
    branches:
      - "main"
      - "develop"
      - "feat/*"
      - "feature/*"
    paths:
      - "web/client/**"
      - ".github/workflows/web-client-pr-check.yml"

jobs:
  client:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    defaults:
      run:
        working-directory: web/client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use pnpm 10
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
        #   pnpm-version: latest
        #   cache: 'pnpm'
        #   cache-dependency-path: ./web/client/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - run: pnpm lint
      - run: pnpm format -- --write=false

      # - name: Test
      #   run: pnpm run test

      - run: pnpm exec tsc --noEmit
      - run: pnpm build